const express = require("express");
const router = express.Router();
const groupRouter = require("./GroupRouter");
const hostRouter = require("./HostRouter");
const registerController = require("../controller/RegisterController");
const loginController = require("../controller/LoginController");
const searchController = require("../controller/SearchController");
const otherController = require("../controller/OtherController");
router.post("/register", registerController.register);
router.post("/login", loginController.login);
router.get("/search", searchController.search);
router.get("/roominfo", searchController.showDetailInfo);
router.post("/rent", otherController.rentRequest);
router.use("/group", groupRouter);
router.use("/host", hostRouter);
module.exports = router;
